config/routes.rb
Rails.application.routes.draw do
  root to: 'country_play_list#index'
  resources :country_play_list, only: [:index, :show]
  resources :import_csvs do
    collection do
      post :import
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :tracks, dependent: :destroy
  validates :name, presence: true 
   
  def self.get(author)
    if author.present?
      where(name: author).first
    else
      nil
    end    
  end  
end

app/models/country.rb
class Country < ApplicationRecord
  has_many :country_play_lists, dependent: :destroy
  validates :name, presence: true

  def self.get(country)
    if country.present?
      where(name: country).first
    else
      nil
    end    
  end
    
end

app/models/country_play_list.rb
class CountryPlayList < ApplicationRecord
  belongs_to :track
  belongs_to :country

  validates :track_id, :country_id, :year, presence: true

  scope :year, -> (year) { where(year: year) }
  default_scope { order(score: :desc) }


  def self.get(country, year)
    if country.present? && year.present?
      where(country: country, year: year)
    else
      nil
    end    
  end 
end

app/models/import_csv.rb
class ImportCsv < ApplicationRecord
  mount_uploader :csv, CsvUploader
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :author
  validates :name, :link, :author_id, presence: true
  
  def self.get(name, author)
    if name.present?
      where(name: name, author: Author.get(author)).first
    else
      nil
    end    
  end     
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
  layout proc {
    if request.xhr?
      false
    else
      "application"
    end
  }
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
  end

  def show
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @playlist = Country.find(params[:id])
    end
end

app/controllers/country_play_list_controller.rb
class CountryPlayListController < ApplicationController
  before_action :set_country_playlist, only: [:show]

  def index
    @playlists = CountryPlayList.where(country: Country.get(params[:country]), 
      year: params[:year])
  end

  private
    def set_country_playlist
      @playlists = CountryPlayList.where(country: Country.get(params[:country]),
       year: params[:year])
    end
end

app/controllers/import_csvs_controller.rb
class ImportCsvsController < ApplicationController
  require 'csv'

  def import
    csv = ImportCsv.new
    begin   
      csv.csv = params[:file]
      if csv.save!
        CsvImportService.new({path: csv.csv.path}).upload
        @res = {success: true, msg: "File will be uploaded"}
        status_code = 200
      end
    rescue ActiveRecord::RecordInvalid
      @res = {success: false, msg: csv.errors.messages[:csv][0]}
      status_code = 400
    end  
    render json: @res, status: status_code    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/import_csvs_helper.rb
module ImportCsvsHelper
end

app/views/countries/index.html.slim
.content
  h1 Markup examples
  p This example shows you how a basic Slim file looks.

app/views/country_play_list/index.html.slim
.country-play-list
  .sidebar
    .cover.no-img
      /= image_tag 'no-img'
    .play-list 
      div ng-repeat="el in ctrl.playlist"
        .track
          .cover
            img src="{{el.track.cover}}"
          .track-info
            .track-name ng-bind="el.track.name | limitTo:34"
            .author ng-bind="el.track.author"

    div
      /форма загрузки csv, кстати коменты в html не отрендарятся
      /=render "import_csvs/form"
  #map

app/views/import_csvs/_form.html.slim
.import_csv
  form ng-app="fileUpload" name="form" validcsv=""
    .form-group 
      label ng-show="file" Downloaded {{file.name}}
      button ngf-select="" ng-model="file" name="file" validcsv="" Select

      button type="submit" ng-click="submit()" Submit

app/views/import_csvs/index.html.slim
h1 Listing import_csvs

table
  thead
    tr
      th
      th
      th

  tbody
    - @import_csvs.each do |import_csv|
      tr
        td = link_to 'Show', import_csv
        td = link_to 'Edit', edit_import_csv_path(import_csv)
        td = link_to 'Destroy', import_csv, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Import csv', new_import_csv_path

app/views/layouts/application.html.slim
html ng-app="app"
  head
    title MAD
    base href="/"
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
  body
    ui-view
      /= yield